//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuyuruPlatform.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUYURU_OKUNDUBILGI
    {
        public int ID { get; set; }
        public int DUYURU_ID { get; set; }
        public int KULLANICI_ID { get; set; }
        public bool OKUNDU { get; set; }
    
        public virtual DUYURU DUYURU { get; set; }
        public virtual KULLANICI_BILGILERI KULLANICI_BILGILERI { get; set; }
    }
}
